config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "landing_page#index"

  get '/auth/:provider/callback', to: 'authorization#omniauth'
  # registration user controller
  get '/sign_up', to: 'registrations#new'
  post '/sign_up', to: 'registrations#create'
  get '/sign_up/verification', to: 'registrations#edit'
  delete 'destroy', to: 'registrations#destroy', as: 'destroy'
  patch '/sign_up/verification', to: 'registrations#update'
  get '/sign_up/verification/resend/', to: 'registrations#resend', as: 'resend'

  # registration coach controller
  get '/become_coach', to: 'registration_coaches#new'
  post '/become_coach', to: 'registration_coaches#create'
  delete 'destroy_coach', to: 'registration_coaches#destroy', as: 'back_to_sign_up'
  get '/become_coach/update', to: 'registration_coaches#edit'
  patch '/become_coach/update', to: 'registration_coaches#update'
  get '/become_coach/update/resend/', to: 'registration_coaches#resend', as: 'resend_coach'


  # authorization user controller
  get '/sign_in', to: 'authorization#new'
  post '/sign_in', to: 'authorization#create'
  delete 'logout', to: 'authorization#destroy'

  # authorization coach controller
  get '/sign_in/coach', to: 'authorization_coach#new'
  post '/sign_in/coach', to: 'authorization_coach#create'
  delete 'logout_coach', to: 'authorization_coach#destroy', as: 'logout_coach'

  # user contoller
  get '/user/', to: 'user#dashboard', as: 'user_page'
  get '/user/update', to: 'user#edit', as: 'update_profile_user'
  patch '/user/update', to: 'user#update'
  get '/user/password_change', to: 'user#password_edit', as: 'password_change_user'
  patch '/user/password_change', to: 'user#password_update'
  get '/user/dashboard', to: 'user#dashboard', as: 'user_dashboard_page'
  get '/user/coaches', to: 'user#coaches_page', as: 'user_coahes_page'
  get '/user/coaches/invitation/:coach_id', to: "user#new", as: 'invitation'
  post 'user/coaches/invitation/:coach_id', to: "user#send_invintation"
  delete 'cancel/:invite_id', to: 'user#cancel_invite', as: 'cancel_coach_invite'
  get '/user/ask', to: 'user#modal_ask_form', as: 'asking_form'
  delete 'end/:invite_id', to: 'user#end_cooperation', as: 'end_cooperation_coach_invite'
  get '/user/dashboard/:technique_id/step/:step_id', to: 'user#user_technique_detail', as: 'user_technique_detail'
  patch '/user/dashboard/:technique_id/step/:step_id', to: 'user#restart', as: 'restart'
  get '/user/my_techniques', to: 'user#my_techniques', as: 'user_techniques_page'
  get '/user/dashboard/:technique_id/step/:step_id/rate', to: 'user#finish', as: 'user_rate_window'
  post '/user/dashboard/:technique_id/step/:step_id/rate', to: 'user#like', as: 'like_rating'
  post '/user/dashboard/:technique_id/step/:step_id/rate/dislike', to: 'user#dislike', as: 'dislike_rating'
  # coach contoller
  get '/coach/', to: 'coach#dashboard', as: 'coach_page'
  get '/coach/update', to: 'coach#edit', as: 'update_profile_coach'
  patch '/coach/update', to: 'coach#update'
  get '/coach/password_change', to: 'coach#password_edit', as: 'password_change_coach'
  patch '/coach/password_change', to: 'coach#password_update'
  get '/coach/dashboard', to: 'coach#dashboard', as: 'coach_dashboard_page'
  get '/coach/my_users', to: 'coach#coach_users', as: 'coach_users_page'
  get '/coach/library', to: 'coach#library', as: 'coach_library_page'
  delete 'refuse/:invite_id', to: 'coach#refuse', as: 'refuse_user_invite'
  patch 'confirm/:invite_id', to: 'coach#confirm', as: 'confirm_user_invite'
  get '/coach/library/:technique_id', to: 'coach#technique_detail', as: 'technique_detail_page'
  get '/coach/library/:technique_id/recommendation', to: 'coach#new', as: 'recommend_to_users_page'
  post '/coach/library/:technique_id/recommendation', to: 'coach#create'
  get '/coach/user/:user_id/detail', to: 'coach#user_detail', as: 'user_detail'



  # reset password contoller
  get '/reset_password/new', to: 'reset_password#new'
  post '/reset_password/new', to: 'reset_password#create'
  get '/reset_password/edit', to: 'reset_password#edit'
  patch '/reset_password/edit', to: 'reset_password#update'
  get '/reset_password/edit/resend/', to: 'reset_password#resend', as: 'resend_user_reset'

  # reset password coach controller
  get '/reset_password_coach/new', to: "reset_password_coach#new"
  post '/reset_password_coach/new', to: "reset_password_coach#create"
  get '/reset_password_coach/edit', to: "reset_password_coach#edit"
  patch '/reset_password_coach/edit', to: "reset_password_coach#update"
  get '/reset_password_coach/edit/resend/', to: 'reset_password_coach#resend', as: 'resend_coach_reset'

  # api authorization user

  namespace :api do
    post '/auth/user/login', to: 'authorization#login'
    post '/auth/user/registration', to: 'registration#registration'
    get '/auth/user/detail', to: 'user#show'
  end
end

app/models/coach.rb
class Coach < ApplicationRecord
  include SearchCoach

  has_many :users
  has_many :social_networks
  has_many :coach_notifications
  has_and_belongs_to_many :problems

  has_many :invitations
  has_many :users, through: :invitations

  has_many :recommendations
  has_many :users, through: :recommendations

  has_many :recommendations
  has_many :techniques, through: :recommendations

  has_one_attached :avatar

  has_secure_password

  PASSWORD_FORMAT = /\A
    (?=.{8,})          # Must contain 8 or more characters
    (?=.*[a-z])        # Must contain a lower case character
    (?=.*[A-Z])        # Must contain an upper case character
    (?=.*[[:^alnum:]]) # Must contain a symbol
  /x

  validates :password, presence: true, format: { with: PASSWORD_FORMAT }, allow_nil: true

  validates :age, presence: false
  validates :abouts, presence: false
  validates :gender, presence: false
  validates :experience, presence: false
  validates :education, presence: false
  validates :licenses, presence: false

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
  enum gender: [ :male, :female ]
end

app/controllers/coach_controller.rb
class CoachController < ApplicationController
  before_action :require_coach_logged_in!
  def show
    @coach = Current.coach
  end

  def dashboard
    @coach = Current.coach
    @problems = @coach.problems
    @notifications = @coach.coach_notifications.order('created_at desc')
    @invitation = @coach.invitations.where(status: 1)
    @total_user = User.all.count
    recommendations = @coach.recommendations
    techniques_ids = recommendations.pluck(:technique_id).uniq
    @techniques = []
    techniques_ids.each { |id| @techniques << Recommendation.find_by(technique_id: id, coach_id: @coach.id) }
    @technique_in_used = recommendations.pluck(:technique_id).uniq.length
    @total_coach_users = @coach.invitations.where(status: 1).count
    @user_data = get_techniques_in_progress(@invitation)
    @total_likes = count_likes_on_techniques(@techniques)
  end

  def library
    @coach = Current.coach
    @problems = Problem.all
    if params[:search].present?
      search_techniques(params[:search])
    else
      if params[:filter].present?
        filter_status(params[:filter][:status])
        filter_problems(params[:filter][:problems])
        filter_gender(params[:filter][:gender])
      else
        @technigues = Technique.all
      end
    end
  end

  def technique_detail
    @coach = Current.coach
    @technique = Technique.find_by_id(params[:technique_id])
    @steps = Step.where(techniques_id: @technique.id)
  end

  def new
    @coach = Current.coach
    @users = @coach.invitations.where(status: 1)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @coach = Current.coach
    @technique = Technique.find_by_id(params[:technique_id])
    users_names_list = params[:users].select! { |element| element&.size.to_i > 0 }
    users_names_list.each do |user_name|
      user = User.find_by(name: user_name)
      if Recommendation.find_by(user_id: user.id, technique_id: @technique.id) == nil
        Recommendation.create(user_id: user.id, coach_id: @coach.id, technique_id: @technique.id, status: 0, step: 0)
        UserNotification.create(body: "Coach #{@coach.name} recommended a Technique for you", user_id: user.id, coach_id: @coach.id ,status: 1)
      else
        flash[:warning] = "User #{user_name} is alraedy passed this technique!"
      end
    end
    redirect_to coach_users_page_path
  end

  def coach_users
    @coach = Current.coach
    @notifications = CoachNotification.where.not(user_id: nil).where(coach_id: @coach.id)
    @count = Invitation.where(coach_id: @coach.id, status: 0).count
    @invitation = Invitation.where(coach_id: @coach.id)
    @user_data = get_techniques_in_progress(@invitation)
  end

  def refuse
    @invite = Invitation.find_by_id(params[:invite_id])
    CoachNotification.create(body: "You have rejected #{@invite.user.name} invite", coach_id: @invite.coach.id, user_id: @invite.user.id, status: 1)
    UserNotification.create(body: "Coach #{@invite.coach.name} refused to become your coach", user_id: @invite.user.id, coach_id: @invite.coach.id, status: 1)
    @invite.destroy
    flash[:info] = "You refused user invite!"
    redirect_to coach_users_page_path
  end

  def confirm
    @invite = Invitation.find_by_id(params[:invite_id])
    UserNotification.create(body: "Coach #{@invite.coach.name} agreed to become your coach", user_id: @invite.user.id, status: 1)
    CoachNotification.create(body: "You agreed to become a coach for a user #{@invite.user.name}", coach_id: @invite.coach.id, user_id: @invite.user.id, status: 1)
    @invite.update(status: 1)
    flash[:info] = "You agreed to become a coach for a user #{@invite.user.name}!"
    redirect_to coach_users_page_path
  end

  def edit
    @coach = Current.coach
    @problems = Problem.all
  end

  def update
    @coach = Current.coach
    @problems = Problem.all
    if @coach.update(update_params)
      if params[:coach][:social_networks] && params[:coach][:social_networks] != ""
        params[:coach][:social_networks].each do |social_network|
          SocialNetwork.create(name: social_network, coach_id: @coach.id)
        end
      end
      params[:coach][:problems]&.each do |problem|
        @problems.each do |data|
          if problem == data[:name]
            if @coach.problems.find_by(name: data[:name]) == nil
              @coach.problems << data
            end
          end
        end
      end
      CoachNotification.create(body: "You changed your profile settings", status: 1, coach_id: @coach.id)
      flash[:info] = "You updated your profile info!"
      redirect_to coach_page_path
    else
      render :edit
    end
  end

  def password_edit
    @coach = Current.coach
  end

  def password_update
    @coach = Current.coach
    if BCrypt::Password.new(Current.coach.password_digest) == params[:coach][:old_password]
      if Current.coach.update(password_params)
        CoachNotification.create(body: "You changed your password settings", status: 1, coach_id: @coach.id)
        flash[:info] = "You changed your password!"
        redirect_to coach_page_path
      else
        render :password_edit
      end
    else
      flash[:error] = "You entered invalid password!"
      render :password_edit
    end
  end

  def user_detail
    @coach = Current.coach
    @invitation = Invitation.find_by(user_id: params[:user_id])
    @recommendations = Recommendation.where(user_id: params[:user_id])
    get_total_time_for_techniques(@recommendations)
    get_current_time_for_techniques(@recommendations)
    @notifications = CoachNotification.where(coach_id: @coach.id, user_id: @invitation.user.id)
  end

  private

  def get_total_time_for_techniques(techniques)
    @total_hours = 0
    techniques&.each do |t|
      if t.status == 'compeleted'
        @total_hours += (t.ended_at - t.started_at)/60/60
      end
    end
    @total_hours = @total_hours.round
  end

  def get_current_time_for_techniques(techniques)
    @current_hours = 0
    techniques&.each do |t|
      if t.status == 'in_progress'
        @current_hours += (Time.zone.now - t.started_at)/60/60
      end
    end
    @current_hours = @current_hours.round
  end


  def search_techniques(param)
    @technigues = Technique.search(param)
  end

  def filter_status(param)
    @technigues = Technique.all
    param&.each do |p|
      if p == "recommend"
        @technigues, techniques_ids = [], []
        Recommendation.where(coach_id: Current.coach.id).each { |data| techniques_ids << data.technique_id }
        techniques_ids.uniq!
        techniques_ids.each { |id| @technigues << Technique.find_by_id(id) }
      else
        @technigues = []
        technigues_where_status = Technique.where(p)
        technigues_where_status.each do |data|
          if data.recommendations.where(coach_id: Current.coach.id) == []
            @technigues << data
          end
        end
      end
    end

  end

  def filter_gender(param)
    param&.each do |data|
      @technigues = @technigues.where(data)
    end
  end

  def filter_problems(param)
    if param.present?
      @technigues = Problem.find_by(name: param).techniques
    end
  end

  def get_techniques_in_progress(invitation)
    user_data = {}
    invitation.each do |data|
      user_data[data.user.email] = []
      user_recommendations = data.user.recommendations
      user_recommendations.each do |recommendation|
        if recommendation.status == 'in_progress'
          user_data[data.user.email] << recommendation.technique.title
        end
      end
      user_data[data.user.email] << "All techniques completed" if user_data[data.user.email] == []
    end
    user_data
  end

  def count_likes_on_techniques(recommendations)
    techniques_ids = []
    total_likes = 0
    recommendations.each do |data|
      techniques_ids << data.technique_id
    end
    techniques_ids.uniq!
    techniques_ids.each { |id| total_likes += Rating.where(technique_id: id).sum(:like)}
    total_likes
  end

  def update_params
    params.require(:coach).permit(:name, :email, :avatar, :about, :age, :gender, :education, :experience, :licenses)
  end

  def password_params
    params.require(:coach).permit(:password, :password_confirmation)
  end
end

app/views/coach/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title">Recommend to your users</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <%= form_with url: recommend_to_users_page_path do |f| %>
    <% @users.each do |user|%>
        <%= f.check_box :users,  {:multiple => true}, user.user.name, '' %>
        <%= f.label :users, user.user.name %>
        <br>
    <% end %>
    <br>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCEL</button>
    <%= f.submit "SEND", class: "btn btn-send"%>
  <% end %>

</div>

app/views/coach/coach_users.html.erb
<% content_for :content do %>



<div class="row">

  <div class="col-8">
    <div class="row-width">

      <div class="row">

        <div class="col-6 my-users-page active-page">
          <button id="my-users">My users</button>
        </div>
        <div class="col-6 my-users-page">
          <button id="waiting">Waiting for confirmation (<%= @count %>)</button>
        </div>

      </div>

      <div id="div-waiting-users">
        <div class="row">
          <% if @invitation %>
            <% @invitation.each do |value| %>
              <% if value.status == false %>
                <div class="col-6">
                  <br>
                  <div class="card">
                    <div class="body">
                      <div class="small-card">
                        <div class="image-avatar-small">
                          <% if value.user.avatar_user.attached? %>
                            <img src="<%= url_for(value.user.avatar_user) %>" class="rounded-circle avatar-coach-users">
                          <% else %>
                            <img src="<%= asset_path('generic-user-icon-10.png') %>" class="rounded-circle avatar-coach-users">
                          <% end %>

                        </div>
                        <div class="name-coach">
                          <span class="coach-name"><%= value.user.name %></span><br>
                          <span class="status">User</span>
                          <p class="coach-info-left"><%= value.user.age %> years | <%= value.user.gender %></p>
                          <% if value.user.about %>
                            <p class="coach-info-left"><%= value.user.about %></p>
                          <% end %>
                          <div class="edit-prof-coach">
                            <i class="bi bi-envelope"></i>
                          </div>
                        </div>
                        <div class="about-user">
                          <p class="tages-info">Problems</p>
                          <% value.user.problems.each do |problem|%>
                            <span class="tags"><%= problem.name%></span>
                          <% end %>

                          <div class="buttons-list">
                            <%= button_to 'CONFIRM', confirm_user_invite_path(value.id), method: :patch, class:"button-confirm"%>
                            <%= button_to 'REFUSE', refuse_user_invite_path(value.id), method: :delete, class:"button-refuse" %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <p>You don't confirm any invitayions!</p>
          <% end %>

        </div>
      </div>
      <div id="div-my-users">
        <div class="row">
          <% if @invitation %>
            <% @invitation.each do |value| %>
              <% if value.status == true %>
                <div class="col-6">
                  <br>
                  <div class="card">
                    <div class="body">
                      <div class="small-card">
                        <div class="image-avatar-small">
                          <% if value.user.avatar_user.attached? %>
                            <img src="<%= url_for(value.user.avatar_user) %>" class="rounded-circle avatar-coach-users">
                          <% else %>
                            <img src="<%= asset_path('generic-user-icon-10.png') %>" class="rounded-circle avatar-coach-users">
                          <% end %>

                        </div>
                        <div class="name-coach">
                          <span class="coach-name"><%= value.user.name %></span><br>
                          <span class="status">Current user</span>
                          <p class="coach-info-left"><%= value.user.age %> years | <%= value.user.gender %></p>
                          <div class="edit-prof-coach">
                            <i class="bi bi-envelope"></i>
                          </div>
                        </div>
                        <div class="about-user">
                          <p class="tages-info">Problems</p>
                          <% value.user.problems.each do |problem|%>
                            <span class="tags"><%= problem.name%></span>
                          <% end %>
                          <p class="tages-info">Techniques in process</p>
                          <% @user_data[value.user.email].each do |value|%>
                            <% if value == "All techniques completed" %>
                              <p class="completed_techniques"><%= value %></p>
                            <% else %>
                              <p class="user-t-info"><%= value %></p>
                            <% end %>
                          <% end %>
                          <div class="see-detail-button"><%= link_to 'SEE DETAILS', user_detail_path(user_id: value.user.id), class: "get_down_link"%></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <p>You don't confirm any invitayions!</p>
          <% end %>

        </div>
      </div>


    </div>
  </div>
  <script type="text/javascript">
    $('#waiting').click(function (){
      $('#div-waiting-users').show();
      $('#div-my-users').hide();
    });
    $('#my-users').click(function (){
      $('#div-my-users').show();
      $('#div-waiting-users').hide();
    });
  </script>

  <div class="col-4">

    <div class="row-width">
      <div class="row">
        <div class="col-12 notifications-title">
          User's Notifications
        </div>

      </div>
      <% if @notifications %>
      <div class="layer">
        <% @notifications.reverse_each do |data| %>
          <div class="row">
            <div class="col-2 notif-avatar-block">
              <% if data.coach_id && data.user_id%>
                <img src="<%= asset_path('generic-user-icon-10.png') %>" class="rounded-circle notification-avatar">
              <% else %>
                <% if @coach.avatar.attached? %>
                  <img src="<%= url_for(@coach.avatar) %>" class= "rounded-circle notification-avatar">
                <% else %>
                  <img src="<%= asset_path('generic-user-icon-10.png') %>" class="rounded-circle notification-avatar">
                <% end %>
              <% end %>

            </div>
            <div class="col-7">
              <p class="notif-text-block"><%= data.body %></p>
              <p class="notif-hours-block"><%= time_lasted_since(data.created_at, data)%></p>
            </div>
            <div class="col-3 notif-tag-block ">
              <% if data.status == true %>
                  <span class="badge-tag">NEW</span>
              <% else %>

              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>

    </div>

  </div>

</div>

<% end %>
<%= render template: "coach/show" %>

app/views/coach/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'coach/new') %>");
$("#modal-window").modal();

app/views/coach/show.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
  <nav class="navbar navbar-expand-lg nav_background fixed-top">
    <div class="container-fluid pad">
      <a class="navbar-brand logo logo-button" href="#">Logo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to 'Dashboard', coach_dashboard_page_path, class: "nav-link nav-link-style"%>
          <%= link_to 'My users', coach_users_page_path, class: "nav-link nav-link-style"%>
          <%= link_to 'Library', coach_library_page_path, class: "nav-link nav-link-style"%>
        </div>
      </div>
      <div class="d-flex">
        <div class="envelope-block"><i class="bi bi-envelope"></i></div>

        <div class="bell-block">
          <i class="bi bi-bell" ></i>

        </div>
        <div class="me-3 dropdown">
          <% if @coach.avatar.attached? %>
            <img src="<%= url_for(@coach.avatar) %>" class= "rounded-circle size-image" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
          <% else %>
            <img src="<%= asset_path('sydney-sims-fZ2hMpHIrbI-unsplash.jpg') %>" class="rounded-circle size-image" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Personal Information', update_profile_coach_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Change Password', password_change_coach_path, class: "dropdown-item" %></li>
          </ul>
        </div>
        <%= button_to 'LOG OUT', logout_coach_path, method: :delete, class: "btn btn-sing-in" %>
      </div>
    </div>
  </nav>

  <div class="content-block">
    <% flash.each do |type, msg| %>
      <% if type == 'warning' %>
        <div class="alert alert-warning d-flex alert-dismissible fade show warning-color" role="alert">
          <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
          <div><%= msg %></div>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% elsif type == 'info' %>
        <div class="alert alert-primary  d-flex alert-dismissible fade show warning-color" role="alert">
          <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
          <div><%= msg %></div>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% else %>
        <div class="alert alert-danger  d-flex alert-dismissible fade show warning-color" role="alert">
          <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
          <div><%= msg %></div>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    <% end %>

    <%= content_for?(:content) ? yield(:content) : yield %>


  </div>

app/views/coach/technique_detail.html.erb
<% content_for :content do %>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

<h6>
  <%= link_to "Go back", coach_library_page_path, class: "bi bi-chevron-left link-back" %>
</h6>
<br>

<div class="row">

  <div class="col-8">
    <div class="row-width">
      <div class="row">
        <div class="col-12 mt">
          <%= @technique.title %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-4"></div>
</div>
<br>
<br>

<div class="row">
  <div class="col-8">
    <div class="row-width">
      <div class="layer">
        <% @steps.each do |step|%>
          <div class="row">
            <div class="col-12">
              <h6> Step <%= step.number %> </h6>
            </div>
            <div class="col-12">
              <div class="card">
                <div class="body_pad">
                    <p class="step-title-card"><%= step.title %></p>
                    <span><%= step.body %></span>
                    <br>
                    <video width="100%" height="300px" controls src="https://www.youtube.com/watch?v=Jt6ZyyUyK0k">
                      Your browser does not support the video tag.
                    </video>
                </div>

              </div>
            </div>
          </div>
          <br>
        <% end %>
      </div>
    </div>

  </div>
  <div class="col-4">
    <div class="row">

      <div class="col-12 pading-recoomend-card ">


        <div class="card h-100">
          <div class="item">
            <% if @technique.photo.attached? %>
              <img src="<%= url_for(@technique.photo) %>" class= "card-img-top" alt="...">
            <% else %>
              <img src="<%= asset_path('anthony-tran-vXymirxr5ac-unsplash.jpg') %>" class="card-img-top" alt="...">
            <% end %>
            <% if @technique.problems %>
              <div class="tags-div-absolute">
                <% @technique.problems.each do |problem|%>
                  <span class="tags-in-image "><%= problem.name%></span>
                <% end %>
              </div>
            <% end %>

          </div>
          <div class="card-body">
            <h6 class="title_card"><%= @technique.title %></h6>

            <p class="description"><%= @technique.description %></p>
            <div class="age">Age: <strong><%= @technique.age %> years</strong></div>
            <div class="gender">Gender: <strong><%= @technique.gender %></strong></div>
            <br>
            <div class="step">Steps:<strong> <%= @technique.total_steps %></strong></div>
            <div class="duration">Duration:<strong> <%= @technique.duration %> </strong></div>
            <ul class="hr">
              <li><i class="bi bi-people"></i> <%= Recommendation.where(technique_id: @technique.id).count%></li>
              <li><i class="bi bi-hand-thumbs-up"></i> <%= Rating.where(technique_id: @technique.id).sum(:like)%></li>
              <li><i class="bi bi-hand-thumbs-down"></i> <%= Rating.where(technique_id: @technique.id).sum(:dislike)%></li>
              <li class="start-button"><%= link_to 'RECOMMEND', recommend_to_users_page_path,  {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#modal-window', class: "get_down_link"}  %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>

<% end %>
<%= render template: "coach/show" %>