config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "landing_page#index"

  get '/auth/:provider/callback', to: 'authorization#omniauth'
  # registration user controller
  get '/sign_up', to: 'registrations#new'
  post '/sign_up', to: 'registrations#create'
  get '/sign_up/verification', to: 'registrations#edit'
  delete 'destroy', to: 'registrations#destroy', as: 'destroy'
  patch '/sign_up/verification', to: 'registrations#update'
  get '/sign_up/verification/resend/', to: 'registrations#resend', as: 'resend'

  # registration coach controller
  get '/become_coach', to: 'registration_coaches#new'
  post '/become_coach', to: 'registration_coaches#create'
  delete 'destroy_coach', to: 'registration_coaches#destroy', as: 'back_to_sign_up'
  get '/become_coach/update', to: 'registration_coaches#edit'
  patch '/become_coach/update', to: 'registration_coaches#update'
  get '/become_coach/update/resend/', to: 'registration_coaches#resend', as: 'resend_coach'


  # authorization user controller
  get '/sign_in', to: 'authorization#new'
  post '/sign_in', to: 'authorization#create'
  delete 'logout', to: 'authorization#destroy'

  # authorization coach controller
  get '/sign_in/coach', to: 'authorization_coach#new'
  post '/sign_in/coach', to: 'authorization_coach#create'
  delete 'logout_coach', to: 'authorization_coach#destroy', as: 'logout_coach'

  # user contoller
  get '/user/', to: 'user#dashboard', as: 'user_page'
  get '/user/update', to: 'user#edit', as: 'update_profile_user'
  patch '/user/update', to: 'user#update'
  get '/user/password_change', to: 'user#password_edit', as: 'password_change_user'
  patch '/user/password_change', to: 'user#password_update'
  get '/user/dashboard', to: 'user#dashboard', as: 'user_dashboard_page'
  get '/user/coaches', to: 'user#coaches_page', as: 'user_coahes_page'
  get '/user/coaches/invitation/:coach_id', to: "user#new", as: 'invitation'
  post 'user/coaches/invitation/:coach_id', to: "user#send_invintation"
  delete 'cancel/:invite_id', to: 'user#cancel_invite', as: 'cancel_coach_invite'
  get '/user/ask', to: 'user#modal_ask_form', as: 'asking_form'
  delete 'end/:invite_id', to: 'user#end_cooperation', as: 'end_cooperation_coach_invite'
  get '/user/dashboard/:technique_id/step/:step_id', to: 'user#user_technique_detail', as: 'user_technique_detail'
  patch '/user/dashboard/:technique_id/step/:step_id', to: 'user#restart', as: 'restart'
  get '/user/my_techniques', to: 'user#my_techniques', as: 'user_techniques_page'
  get '/user/dashboard/:technique_id/step/:step_id/rate', to: 'user#finish', as: 'user_rate_window'
  post '/user/dashboard/:technique_id/step/:step_id/rate', to: 'user#like', as: 'like_rating'
  post '/user/dashboard/:technique_id/step/:step_id/rate/dislike', to: 'user#dislike', as: 'dislike_rating'
  # coach contoller
  get '/coach/', to: 'coach#dashboard', as: 'coach_page'
  get '/coach/update', to: 'coach#edit', as: 'update_profile_coach'
  patch '/coach/update', to: 'coach#update'
  get '/coach/password_change', to: 'coach#password_edit', as: 'password_change_coach'
  patch '/coach/password_change', to: 'coach#password_update'
  get '/coach/dashboard', to: 'coach#dashboard', as: 'coach_dashboard_page'
  get '/coach/my_users', to: 'coach#coach_users', as: 'coach_users_page'
  get '/coach/library', to: 'coach#library', as: 'coach_library_page'
  delete 'refuse/:invite_id', to: 'coach#refuse', as: 'refuse_user_invite'
  patch 'confirm/:invite_id', to: 'coach#confirm', as: 'confirm_user_invite'
  get '/coach/library/:technique_id', to: 'coach#technique_detail', as: 'technique_detail_page'
  get '/coach/library/:technique_id/recommendation', to: 'coach#new', as: 'recommend_to_users_page'
  post '/coach/library/:technique_id/recommendation', to: 'coach#create'
  get '/coach/user/:user_id/detail', to: 'coach#user_detail', as: 'user_detail'



  # reset password contoller
  get '/reset_password/new', to: 'reset_password#new'
  post '/reset_password/new', to: 'reset_password#create'
  get '/reset_password/edit', to: 'reset_password#edit'
  patch '/reset_password/edit', to: 'reset_password#update'
  get '/reset_password/edit/resend/', to: 'reset_password#resend', as: 'resend_user_reset'

  # reset password coach controller
  get '/reset_password_coach/new', to: "reset_password_coach#new"
  post '/reset_password_coach/new', to: "reset_password_coach#create"
  get '/reset_password_coach/edit', to: "reset_password_coach#edit"
  patch '/reset_password_coach/edit', to: "reset_password_coach#update"
  get '/reset_password_coach/edit/resend/', to: 'reset_password_coach#resend', as: 'resend_coach_reset'

  # api authorization user

  namespace :api do
    post '/auth/user/login', to: 'authorization#login'
    post '/auth/user/registration', to: 'registration#registration'
    get '/auth/user/detail', to: 'user#show'
  end
end

app/controllers/reset_password_coach_controller.rb
class ResetPasswordCoachController < ApplicationController
  def new
  end

  def create
    @coach = Coaches::ResetPassword.call(params)
    PasswordMailer.reset_coach(@coach).deliver_now
    session[:coach_email] = @coach.email
    render :create
  rescue ServiceError => e
    flash.now[:alert] = e.message
    render :new
  end

  def edit
      @coach = Coach.find_signed!(params[:token], purpose: 'reset_password_coach_edit')
      rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_coach_path, alert: 'Your token has expired. Please try again.'
  end


  def update
    @coach = Coach.find_signed!(params[:token], purpose: 'reset_password_coach_edit')

    if @coach.update(password_params)
      session[:coach_email] = nil
      redirect_to sign_in_coach_path, notice: 'Your password was reset successfully. Please sign in'
    else
      render :edit
    end

  end

  def resend
    @coach = Coach.find_by(email: session[:coach_email])
    PasswordMailer.reset_coach(@coach).deliver_now if @coach.present?
    render :create
  end

  private

  def password_params
    params.require(:coach).permit(:password, :password_confirmation)
  end
end

app/views/reset_password_coach/create.html.erb
    <nav class="navbar navbar-expand-lg nav_background fixed-top">
      <div class="container-fluid pad">
        <a class="navbar-brand logo logo-button" href="#">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="conteiner">
      <h6>
        <%= link_to "Go back", sign_in_path, class: "bi bi-chevron-left link-back" %>
      </h6>
      <div class="mail-icon">
        <i class="bi bi-envelope-open"></i>
      </div>
      <h4 class="wait-title">Check your e-mail</h4>
      <p class="help-text">We have sent a password recover instructions to your e-mail</p>
      <p class="help-text"><strong><%= @coach.email %></strong></p>
      <p class="lb">fefe</p>
      <br>
      <p class="verify-text">Did not receive the e-mail? Check your spam filter or</p>

      <p class="verify-text"><strong><%= link_to 'resend', resend_coach_reset_path, class: "resend-link" %></strong></p>
    </div>

app/views/reset_password_coach/edit.html.erb
    <nav class="navbar navbar-expand-lg nav_background fixed-top">
      <div class="container-fluid pad">
        <a class="navbar-brand logo logo-button" href="#">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="conteiner">
        <h4 class="reset-title">Create new password</h4>
        <p class="help-text">Your new password must contain at least 8 characters,</p>
        <p class="help-text">include a number and lowercase letter</p>
        <%= form_with model: @coach, class: "form-registration", url: reset_password_coach_edit_path(token: params[:token]) do |f| %>
          <div class="form-group" data-controller="password-toggle">
            <%= f.label :password, class: "labels" %>
            <%= f.password_field :password, class: "field unhide", autocomplete: "current-password", "data-target": "password-toggle.unhide" %>
            <span data-action="click->password-toggle#password" class="password-field-icon-1 position far bi bi-eye-slash"></span>
          </div>
          <br>

          <div class="form-group" data-controller="password-toggle">
            <%= f.label :password_confirmation, class: "labels" %>
              <%= f.password_field :password_confirmation, class: "field unhide", autocomplete: "current-password", "data-target": "password-toggle.unhide" %>
              <span data-action="click->password-toggle#password" class="password-field-icon-1 position far bi bi-eye-slash"></span>
          </div>
          <br>
          <%= f.submit 'SAVE CHANGES', class: "btn btn-sing-up marge-top" %>
        <% end %>

    </div>

app/views/reset_password_coach/new.html.erb
    <nav class="navbar navbar-expand-lg nav_background fixed-top">
      <div class="container-fluid pad">
        <a class="navbar-brand logo logo-button" href="#">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>

    <div class="conteiner">
      <h6>
        <%= link_to "Go back", sign_in_path, class: "bi bi-chevron-left link-back" %>
      </h6>
      <h4 class="reset-title">Reset password</h4>
      <p class="help-text">Enter the e-mail associated with your account</p>
      <p class="help-text">and we'll send an e-mail with instructions to reset your password.</p>
      <%= form_with class: "form-registration", url: reset_password_coach_new_path do |f| %>
        <div class="form-group">
          <%= f.label 'Email:', class: "labels" %>
          <%= f.text_field :email, class: "field form-control" %>
        </div>
        <%= f.submit 'SEND', class: "btn btn-sing-up marge-top" %>
      <% end %>
    </div>