config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "landing_page#index"

  get '/auth/:provider/callback', to: 'authorization#omniauth'
  # registration user controller
  get '/sign_up', to: 'registrations#new'
  post '/sign_up', to: 'registrations#create'
  get '/sign_up/verification', to: 'registrations#edit'
  delete 'destroy', to: 'registrations#destroy', as: 'destroy'
  patch '/sign_up/verification', to: 'registrations#update'
  get '/sign_up/verification/resend/', to: 'registrations#resend', as: 'resend'

  # registration coach controller
  get '/become_coach', to: 'registration_coaches#new'
  post '/become_coach', to: 'registration_coaches#create'
  delete 'destroy_coach', to: 'registration_coaches#destroy', as: 'back_to_sign_up'
  get '/become_coach/update', to: 'registration_coaches#edit'
  patch '/become_coach/update', to: 'registration_coaches#update'
  get '/become_coach/update/resend/', to: 'registration_coaches#resend', as: 'resend_coach'


  # authorization user controller
  get '/sign_in', to: 'authorization#new'
  post '/sign_in', to: 'authorization#create'
  delete 'logout', to: 'authorization#destroy'

  # authorization coach controller
  get '/sign_in/coach', to: 'authorization_coach#new'
  post '/sign_in/coach', to: 'authorization_coach#create'
  delete 'logout_coach', to: 'authorization_coach#destroy', as: 'logout_coach'

  # user contoller
  get '/user/', to: 'user#dashboard', as: 'user_page'
  get '/user/update', to: 'user#edit', as: 'update_profile_user'
  patch '/user/update', to: 'user#update'
  get '/user/password_change', to: 'user#password_edit', as: 'password_change_user'
  patch '/user/password_change', to: 'user#password_update'
  get '/user/dashboard', to: 'user#dashboard', as: 'user_dashboard_page'
  get '/user/coaches', to: 'user#coaches_page', as: 'user_coahes_page'
  get '/user/coaches/invitation/:coach_id', to: "user#new", as: 'invitation'
  post 'user/coaches/invitation/:coach_id', to: "user#send_invintation"
  delete 'cancel/:invite_id', to: 'user#cancel_invite', as: 'cancel_coach_invite'
  get '/user/ask', to: 'user#modal_ask_form', as: 'asking_form'
  delete 'end/:invite_id', to: 'user#end_cooperation', as: 'end_cooperation_coach_invite'
  get '/user/dashboard/:technique_id/step/:step_id', to: 'user#user_technique_detail', as: 'user_technique_detail'
  patch '/user/dashboard/:technique_id/step/:step_id', to: 'user#restart', as: 'restart'
  get '/user/my_techniques', to: 'user#my_techniques', as: 'user_techniques_page'
  get '/user/dashboard/:technique_id/step/:step_id/rate', to: 'user#finish', as: 'user_rate_window'
  post '/user/dashboard/:technique_id/step/:step_id/rate', to: 'user#like', as: 'like_rating'
  post '/user/dashboard/:technique_id/step/:step_id/rate/dislike', to: 'user#dislike', as: 'dislike_rating'
  # coach contoller
  get '/coach/', to: 'coach#dashboard', as: 'coach_page'
  get '/coach/update', to: 'coach#edit', as: 'update_profile_coach'
  patch '/coach/update', to: 'coach#update'
  get '/coach/password_change', to: 'coach#password_edit', as: 'password_change_coach'
  patch '/coach/password_change', to: 'coach#password_update'
  get '/coach/dashboard', to: 'coach#dashboard', as: 'coach_dashboard_page'
  get '/coach/my_users', to: 'coach#coach_users', as: 'coach_users_page'
  get '/coach/library', to: 'coach#library', as: 'coach_library_page'
  delete 'refuse/:invite_id', to: 'coach#refuse', as: 'refuse_user_invite'
  patch 'confirm/:invite_id', to: 'coach#confirm', as: 'confirm_user_invite'
  get '/coach/library/:technique_id', to: 'coach#technique_detail', as: 'technique_detail_page'
  get '/coach/library/:technique_id/recommendation', to: 'coach#new', as: 'recommend_to_users_page'
  post '/coach/library/:technique_id/recommendation', to: 'coach#create'
  get '/coach/user/:user_id/detail', to: 'coach#user_detail', as: 'user_detail'



  # reset password contoller
  get '/reset_password/new', to: 'reset_password#new'
  post '/reset_password/new', to: 'reset_password#create'
  get '/reset_password/edit', to: 'reset_password#edit'
  patch '/reset_password/edit', to: 'reset_password#update'
  get '/reset_password/edit/resend/', to: 'reset_password#resend', as: 'resend_user_reset'

  # reset password coach controller
  get '/reset_password_coach/new', to: "reset_password_coach#new"
  post '/reset_password_coach/new', to: "reset_password_coach#create"
  get '/reset_password_coach/edit', to: "reset_password_coach#edit"
  patch '/reset_password_coach/edit', to: "reset_password_coach#update"
  get '/reset_password_coach/edit/resend/', to: 'reset_password_coach#resend', as: 'resend_coach_reset'

  # api authorization user

  namespace :api do
    post '/auth/user/login', to: 'authorization#login'
    post '/auth/user/registration', to: 'registration#registration'
    get '/auth/user/detail', to: 'user#show'
  end
end

app/controllers/registration_coaches_controller.rb
class RegistrationCoachesController < ApplicationController
  def new
    @coach = Coach.new
  end

  def create
    @coach = Coaches::Signup.call(coach_params)
    if params[:coach][:agree] == "on"
      CoachMailer.varify_email(@coach).deliver_now
      session[:coach_id] = @coach.id
      render :create
    end
  rescue ServiceError => e
    flash.now[:alert] = e.message
    render :new
  end

  def edit
    @problems = Problem.all
    @coach = Coach.find_signed!(params[:token], purpose: 'become_coach_update')
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
  end

  def update
    @coach = Coach.find_by(id: session[:coach_id]) if session[:coach_id]
    @problems = Problem.all
    if @coach.update(update_params)
      if params[:coach][:social_networks] && params[:coach][:social_networks] != ""
        params[:coach][:social_networks].each do |social_network|
          SocialNetwork.create(name: social_network, coach_id: @coach.id)
        end
      end
      params[:coach][:problems]&.each do |problem|
        @problems.each do |data|
          if problem == data[:name]
            if @coach.problems.find_by(name: data[:name]) == nil
              @coach.problems << data
            end
          end
        end
      end
      redirect_to coach_page_path
    else
      render :edit
    end
  end

  def destroy
    @coach = Coach.find_by(id: session[:coach_id]) if session[:coach_id]
    session[:coach_id] = nil
    @coach.destroy
    redirect_to become_coach_path
  end

  def resend
    @coach = Coach.find_by(id: session[:coach_id]) if session[:coach_id]
    CoachMailer.varify_email(@coach).deliver_now
    render :create
  end

  private

  def coach_params
    params.require(:coach).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:coach).permit(:avatar, :age, :gender, :education, :experience, :licenses)
  end

end

app/views/registration_coaches/create.html.erb
    <nav class="navbar navbar-expand-lg nav_background fixed-top">
      <div class="container-fluid pad">
        <a class="navbar-brand logo logo-button" href="#">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="conteiner">
      <h6>
        <%= link_to "Go back", back_to_sign_up_path,  method: :delete, class: "bi bi-chevron-compact-left link-back" %>
      </h6>
      <div class="mail-icon">
        <i class="bi bi-envelope-open"></i>
      </div>
      <p class="verify">Verify your e-mail</p>
      <p class="verify-text">Click on the link that was sent to the email address you entered: <strong><%= @coach.email %></strong></p>
      <p class="verify-text">to confirm your email address and continue the registration process.</p>

      <p class="lb">fefe</p>

      <br>
      <p class="verify-text">Did not receive the e-mail? Check your spam filter or</p>

      <p class="verify-text"><strong><%= link_to 'resend', resend_coach_path, class: "resend-link" %></strong></p>

    </div>

app/views/registration_coaches/edit.html.erb
    <nav class="navbar navbar-expand-lg nav_background fixed-top">
      <div class="container-fluid pad">
        <a class="navbar-brand logo logo-button" href="#">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="conteiner">
      <h4 class="wait-title">Hello, <strong><%= @coach.name %></strong>!</h4>
      <p class="help-text">You have registered as a Coach in our system.</p>
      <p class="help-text">Please, share some personal information about you so that we can</p>
      <p class="help-text">personalize your onboarding experience</p>

      <%= form_with multipart: true, model: @coach, class: "form-registration", url: become_coach_update_path do |f| %>
        <div class="image-input">
          <img class="rounded-circle" id="output" src="<%= asset_path('png-clipart-graphy-camera-camera-rectangle-photography.png') %>"/>
          <label for="avatar">
            <h4 class="upload">Upload profile photo</h4>
            <p class="upload-text">Image format should be png, jpg</p>
            <p class="upload-text">no more than 5 Mb</p>
          </label>
          <input type="file" accept="image/*" name="coach[avatar]" id="avatar" onchange="loadFile(event)">
          <script>
            var loadFile = function(event) {
              var output = document.getElementById('output');
              output.src = URL.createObjectURL(event.target.files[0]);
              output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
              }
            };
          </script>
        </div>
        <div class="form-group">
          <%= f.label 'Age', class: "labels" %>
          <%= f.text_field :age, class: "field form-control" %>
        </div>
        <br>

        <label class="labels">Gender</label>
        <div class="sign_for_gender">
              <label class="link_for_gender male" for="male">
                <input type="radio" class="female" name="coach[gender]" id="male" value="male">
                <p class="margin-none">MALE</p>
              </label>


              <label class="link_for_gender female" for="female">
                <input type="radio" class="female" name="coach[gender]" id="female" value="female" checked>
                <p class="margin-none">FEMALE</p>
              </label>
        </div>
        <br>
        <div class="form-group">
          <label class="labels" for="tags">Areas of expertise</label>
          <select class="form-control select2-multi" name="coach[problems][]" multiple="multiple">
            <% @problems.each do |data|%>
                <option value="<%= data[:name]%>"><%= data[:name] %></option>
            <% end %>
          </select>
        </div>
        <br>
        <script>
            $('.select2-multi').select2();
        </script>
        <div class="form-group">
          <%= f.label 'Education', class: "labels" %>
          <%= f.text_field :education, class: "field form-control" %>
          <p class="after-input">Name of educational institution, specialty, degree</p>
        </div>
        <div class="add-block">
          <img class="rounded-circle" src="<%= asset_path('add_button.png') %>">
          <label>Add another</label>
        </div>
        <br>

        <div class="form-group">
          <%= f.label 'Work experience', class: "labels" %>
          <%= f.text_field :experience, class: "field form-control" %>
          <p class="after-input">Position, company, work experience</p>
        </div>
        <div class="add-block">
          <img class="rounded-circle" src="<%= asset_path('add_button.png') %>">
          <label>Add another</label>
        </div>
        <br>


        <div class="form-group">
          <%= f.label 'Licenses and certificates', class: "labels" %>
          <%= f.text_field :licenses, class: "field form-control" %>
          <p class="after-input">Name, issuer, date of issue</p>
        </div>
        <div class="add-block">
          <img class="rounded-circle" src="<%= asset_path('add_button.png') %>">
          <label>Add another</label>
        </div>
        <br>


        <div class="form-group" id="networks-block">
          <label for="social_network" class="labels">Link on social networks</label>
          <input type="text" class="field form-control" name="coach[social_networks][]" id="social_network">
          <p class="after-input">E.g., facebook, linkedin, etc.</p>
        </div>
        <div class="add-block">
          <img class="rounded-circle" src="<%= asset_path('add_button.png') %>" onclick="addInput()">
          <label>Add another</label>
        </div>
        <br>
        <script type="text/javascript">
          function addInput() {
            let block = document.getElementById('networks-block')
            let input = document.createElement("input")
            let p = document.createElement("p")
            let text = document.createTextNode("E.g., facebook, linkedin, etc.")
            input.classList.add("field", "form-control")
            input.name = "coach[social_networks][]"
            p.classList.add("after-input", "marge_text")
            block.appendChild(input)
            block.appendChild(p)
            p.appendChild(text)
          }
        </script>

        <%= f.submit 'GET STARTED', class: "btn btn-sing-up marge-top"%>
      <% end %>
    </div>

app/views/registration_coaches/new.html.erb
    <nav class="navbar navbar-expand-lg nav_background fixed-top">
      <div class="container-fluid pad">
        <a class="navbar-brand logo logo-button" href="#">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="conteiner">
      <h4 class="create">Create account</h4>
      <div class="sign_in">
        <div class="ask">Already have an account?</div>
        <div class="link"><%= link_to 'Sign in', sign_in_coach_path, class: "custom"%></div>
      </div>



      <%= form_with model: @coach, class: "form-registration", url: become_coach_path do |f| %>
        <div class="sign_for marge-top">
          <%= link_to "USER", sign_up_path, class: "link_for" %>
          <div class="link_for active">COACH</div>
        </div>
        <br>
        <% if alert %>
          <p class="alert"><%= alert%></p>
        <% end %>
        <% invalid = @coach.errors.include?(:name) %>

        <div class="form-group">
          <%= f.label :name, class: "labels" %>
          <%= f.text_field :name, class: "field form-control #{'is-invalid' if invalid}"%>
          <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @coach.errors.full_messages_for(:name).each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <br>
        <% invalid = @coach.errors.include?(:email) %>

        <div class="form-group">
          <%= f.label :email, class: "labels" %>
          <%= f.text_field :email, class: "field form-control #{'is-invalid' if invalid}" %>
          <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @coach.errors.full_messages_for(:email).each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <br>

        <% invalid = @coach.errors.include?(:password) %>

        <div class="form-group" data-controller="password-toggle">
          <%= f.label :password, class: "labels" %>
          <%= f.password_field :password, class: "field #{'is-invalid' if invalid} unhide", autocomplete: "current-password", "data-target": "password-toggle.unhide" %>
          <span data-action="click->password-toggle#password" class="password-field-icon-1 position far bi bi-eye-slash"></span>
          <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @coach.errors.full_messages_for(:password).each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <br>

        <% invalid = @coach.errors.include?(:password_confirmation) %>

        <div class="form-group" data-controller="password-toggle">
          <%= f.label :password_confirmation, class: "labels" %>
            <%= f.password_field :password_confirmation, class: "field #{'is-invalid' if invalid} unhide", autocomplete: "current-password", "data-target": "password-toggle.unhide" %>
            <span data-action="click->password-toggle#password" class="password-field-icon-1 position far bi bi-eye-slash"></span>
          <% if invalid %>
            <div class="invalid-feedback d-block">
              <% @coach.errors.full_messages_for(:password_confirmation).each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <br>

        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="flexCheckDefault" name="coach[agree]">
          <label class="form-check-label font" for="flexCheckDefault">
            I've read and agree with <strong>Terms of Services</strong> and our <strong>Privacy Policy</strong>
          </label>
        </div>

        <!-- <p class="marge-top">I've read and agree with Terms of Services and our Privacy Policy</p> -->
        <%= f.submit 'SIGN UP', class: "btn btn-sing-up marge-top"%>
        <div class="sign-with">
          <div class="with">
            or Sign in with
          </div>
          <div class="badge-with">
            <i class="bi bi-facebook"></i>
            <i class="bi bi-google"></i>
          </div>
        </div>
      <% end %>
    </div>