config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "landing_page#index"

  get '/auth/:provider/callback', to: 'authorization#omniauth'
  # registration user controller
  get '/sign_up', to: 'registrations#new'
  post '/sign_up', to: 'registrations#create'
  get '/sign_up/verification', to: 'registrations#edit'
  delete 'destroy', to: 'registrations#destroy', as: 'destroy'
  patch '/sign_up/verification', to: 'registrations#update'
  get '/sign_up/verification/resend/', to: 'registrations#resend', as: 'resend'

  # registration coach controller
  get '/become_coach', to: 'registration_coaches#new'
  post '/become_coach', to: 'registration_coaches#create'
  delete 'destroy_coach', to: 'registration_coaches#destroy', as: 'back_to_sign_up'
  get '/become_coach/update', to: 'registration_coaches#edit'
  patch '/become_coach/update', to: 'registration_coaches#update'
  get '/become_coach/update/resend/', to: 'registration_coaches#resend', as: 'resend_coach'


  # authorization user controller
  get '/sign_in', to: 'authorization#new'
  post '/sign_in', to: 'authorization#create'
  delete 'logout', to: 'authorization#destroy'

  # authorization coach controller
  get '/sign_in/coach', to: 'authorization_coach#new'
  post '/sign_in/coach', to: 'authorization_coach#create'
  delete 'logout_coach', to: 'authorization_coach#destroy', as: 'logout_coach'

  # user contoller
  get '/user/', to: 'user#dashboard', as: 'user_page'
  get '/user/update', to: 'user#edit', as: 'update_profile_user'
  patch '/user/update', to: 'user#update'
  get '/user/password_change', to: 'user#password_edit', as: 'password_change_user'
  patch '/user/password_change', to: 'user#password_update'
  get '/user/dashboard', to: 'user#dashboard', as: 'user_dashboard_page'
  get '/user/coaches', to: 'user#coaches_page', as: 'user_coahes_page'
  get '/user/coaches/invitation/:coach_id', to: "user#new", as: 'invitation'
  post 'user/coaches/invitation/:coach_id', to: "user#send_invintation"
  delete 'cancel/:invite_id', to: 'user#cancel_invite', as: 'cancel_coach_invite'
  get '/user/ask', to: 'user#modal_ask_form', as: 'asking_form'
  delete 'end/:invite_id', to: 'user#end_cooperation', as: 'end_cooperation_coach_invite'
  get '/user/dashboard/:technique_id/step/:step_id', to: 'user#user_technique_detail', as: 'user_technique_detail'
  patch '/user/dashboard/:technique_id/step/:step_id', to: 'user#restart', as: 'restart'
  get '/user/my_techniques', to: 'user#my_techniques', as: 'user_techniques_page'
  get '/user/dashboard/:technique_id/step/:step_id/rate', to: 'user#finish', as: 'user_rate_window'
  post '/user/dashboard/:technique_id/step/:step_id/rate', to: 'user#like', as: 'like_rating'
  post '/user/dashboard/:technique_id/step/:step_id/rate/dislike', to: 'user#dislike', as: 'dislike_rating'
  # coach contoller
  get '/coach/', to: 'coach#dashboard', as: 'coach_page'
  get '/coach/update', to: 'coach#edit', as: 'update_profile_coach'
  patch '/coach/update', to: 'coach#update'
  get '/coach/password_change', to: 'coach#password_edit', as: 'password_change_coach'
  patch '/coach/password_change', to: 'coach#password_update'
  get '/coach/dashboard', to: 'coach#dashboard', as: 'coach_dashboard_page'
  get '/coach/my_users', to: 'coach#coach_users', as: 'coach_users_page'
  get '/coach/library', to: 'coach#library', as: 'coach_library_page'
  delete 'refuse/:invite_id', to: 'coach#refuse', as: 'refuse_user_invite'
  patch 'confirm/:invite_id', to: 'coach#confirm', as: 'confirm_user_invite'
  get '/coach/library/:technique_id', to: 'coach#technique_detail', as: 'technique_detail_page'
  get '/coach/library/:technique_id/recommendation', to: 'coach#new', as: 'recommend_to_users_page'
  post '/coach/library/:technique_id/recommendation', to: 'coach#create'
  get '/coach/user/:user_id/detail', to: 'coach#user_detail', as: 'user_detail'



  # reset password contoller
  get '/reset_password/new', to: 'reset_password#new'
  post '/reset_password/new', to: 'reset_password#create'
  get '/reset_password/edit', to: 'reset_password#edit'
  patch '/reset_password/edit', to: 'reset_password#update'
  get '/reset_password/edit/resend/', to: 'reset_password#resend', as: 'resend_user_reset'

  # reset password coach controller
  get '/reset_password_coach/new', to: "reset_password_coach#new"
  post '/reset_password_coach/new', to: "reset_password_coach#create"
  get '/reset_password_coach/edit', to: "reset_password_coach#edit"
  patch '/reset_password_coach/edit', to: "reset_password_coach#update"
  get '/reset_password_coach/edit/resend/', to: 'reset_password_coach#resend', as: 'resend_coach_reset'

  # api authorization user

  namespace :api do
    post '/auth/user/login', to: 'authorization#login'
    post '/auth/user/registration', to: 'registration#registration'
    get '/auth/user/detail', to: 'user#show'
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :coach, optional: true

  has_many :user_notifications

  has_and_belongs_to_many :problems

  has_many :ratings
  has_many :techniques, through: :ratings

  has_many :invitations
  has_many :coaches, through: :invitations

  has_many :recommendations
  has_many :coaches, through: :recommendations

  has_many :recommendations
  has_many :techniques, through: :recommendations

  has_one_attached :avatar_user

  has_secure_password

  PASSWORD_FORMAT = /\A
    (?=.{8,})          # Must contain 8 or more characters
    (?=.*[a-z])        # Must contain a lower case character
    (?=.*[A-Z])        # Must contain an upper case character
    (?=.*[[:^alnum:]]) # Must contain a symbol
  /x


  validates :password, presence: true, format: { with: PASSWORD_FORMAT }, allow_nil: true
  validates :age, presence: false
  validates :abouts, presence: false
  validates :gender, presence: false
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
  enum gender: [ :male, :female ]

  def self.create_from_omniauth(auth)
    User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |user|
        user.name = auth['info']['first_name'] + ' '+auth['info']['last_name']
        user.email = auth['info']['email']
        user.password = SecureRandom.hex(8)+"!"+"A"
    end
  end
end

app/controllers/api/user_controller.rb
module Api
  class UserController < ::ApiController
    before_action :authorize_request

    def show
      @recommendations = @current_user.recommendations
      technique = []
      @recommendations.each { |rec| technique << rec.technique }
      if technique.present?
        render json: { user: @current_user, recommendations: technique }, status: :ok
      else
        render json: { user: @current_user, recommendations: "Not recommendations yet." }, status: :ok
      end
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :require_user_logged_in!

  def new
    @coach = Coach.find_by(id: params[:coach_id])
    @invite = Invitation.find_by(user_id: Current.user.id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def finish
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @user = Current.user
    @problems = Problem.all
  end

  def update
    @user = Current.user
    @problems = Problem.all
    if @user.update(update_params)
      params[:user][:problems]&.each do |problem|
        @problems.each do |data|
          if problem == data[:name]
            if @user.problems.find_by(name: data[:name]) == nil
              @user.problems << data
            end
          end
        end
      end
      UserNotification.create(body: "You changed your profile settings", status: 1, user_id: @user.id)
      flash[:info] = "You updated your profile info!"
      redirect_to user_page_path
    else
      render :edit
    end
  end

  def password_edit
    @user = Current.user
  end

  def password_update
    @user = Current.user
    if BCrypt::Password.new(Current.user.password_digest) == params[:user][:old_password]
      if Current.user.update(password_params)
        UserNotification.create(body: "You changed your password settings", status: 1, user_id: @user.id)
        flash[:info] = "You changed your password!"
        redirect_to user_page_path
      else
        render :password_edit
      end
    else
      flash[:error] = "You entered invalid password!"
      render :password_edit
    end
  end

  def dashboard
    @user = Current.user
    @problems = @user.problems
    @notifications = @user.user_notifications.order('created_at desc')
    @invite = @user.invitations.first
    @recommendations = @user.recommendations.order(:status)
    @total_hours = get_total_time_for_techniques(@recommendations)
    @current_hours = get_current_time_for_techniques(@recommendations)
    @total_competed_techniques = @user.recommendations.where(status: 'compeleted').count
    @total_in_progress_technique = @user.recommendations.where(status: 'in_progress').count
  end

  def user_technique_detail
    @user = Current.user
    @technique = Technique.find_by_id(params[:technique_id])
    @recommendation = Recommendation.find_by(user_id: @user.id, technique_id: params[:technique_id])
    next_step = params[:step_id].to_i
    if next_step < @technique.total_steps
      @recommendation.update(step: next_step+1, status: 1)
      @recommendation.update(started_at: Time.zone.now) if @recommendation.started_at == nil
      @step = Step.find_by(number: next_step+1)
    else
      @step = Step.find_by(number: next_step)
    end
  end

  def restart
    @user = Current.user
    @recommendation = Recommendation.find_by(user_id: @user.id, technique_id: params[:technique_id]).update(step: 0, status: 0, started_at: Time.zone.now, ended_at: nil)
    redirect_to user_technique_detail_path(technique_id: params[:technique_id], step_id: 0)
  end


  def coaches_page
    @user = Current.user
    @problems = Problem.all
    @coaches = Coach.all
    @invite = Invitation.find_by(user_id: @user.id)
    if params[:search] != nil
      search_coach(params[:search])
    else
      if params[:filter].present?
        filter_expertise(params[:filter][:problems])
        filter_users_count(params[:filter][:users])
        filter(params[:filter][:gender])
        filter(params[:filter][:age])
      end
    end
  end

  def send_invintation
    @user = Current.user
    @coach = Coach.find_by_id(params[:coach_id])
    if Invitation.find_by(user_id: @user.id) == nil
      Invitation.create(coach_id: @coach.id, user_id: @user.id, status: 0)
      UserNotification.create(body: "You have sent an invitation to coach #{@coach.name}", user_id: @user.id, coach_id: @coach.id, status: 1)
      CoachNotification.create(body: "You have received an invitation to become a coach from a user #{@user.name}", coach_id: @coach.id, user_id: @user.id, status: 1)
      flash[:info] = "You have sent an invitation to coach!"
      redirect_to user_dashboard_page_path
    end
  end

  def cancel_invite
    @invite = Invitation.find_by_id(params[:invite_id])
    UserNotification.create(body: "You have canceled an invitation to coach #{@invite.coach.name}", user_id: @invite.user.id, coach_id: @invite.coach.id, status: 1)
    flash[:info] = "You have ended cooperation with this coach!"
    @invite.destroy
    redirect_to user_dashboard_page_path
  end

  def modal_ask_form
    @coach = Invitation.find_by(user_id: Current.user.id, status: 1).coach
    @invite = Invitation.find_by(user_id: Current.user.id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def end_cooperation
    @invite = Invitation.find_by_id(params[:invite_id])
    UserNotification.create(body: "You have ended cooperation with coach #{@invite.coach.name}", user_id: @invite.user.id, coach_id: @invite.coach.id, status: 1)
    flash[:info] = "You have ended cooperation with this coach!"
    @invite.destroy
    redirect_to user_dashboard_page_path
  end

  def my_techniques
    @user = Current.user
    @invite = @user.invitations.find_by(status: 1)
    @recommendations = @user.recommendations
  end


  def like
    @user = Current.user
    if Rating.find_by(technique_id: params[:technique_id], user_id: @user.id) == nil
        Rating.create(technique_id: params[:technique_id], user_id: @user.id, like: 1, dislike: 0)
        UserNotification.create(body: "You like your Technique", user_id: @user.id, status: 1)
    end
    recommendation = Recommendation.find_by(technique_id: params[:technique_id], user_id: @user.id)
    recommendation.update(status: 2)
    recommendation.update(ended_at: Time.zone.now) if recommendation.ended_at == nil
    flash[:info] = "You like Technique"
    redirect_to user_dashboard_page_path
  end

  def dislike
    @user = Current.user
    if Rating.find_by(technique_id: params[:technique_id], user_id: @user.id) == nil
        Rating.create(technique_id: params[:technique_id], user_id: @user.id, like: 0, dislike: 1)
        UserNotification.create(body: "You dislike your Technique", user_id: @user.id, status: 1)
    end
    recommendation = Recommendation.find_by(technique_id: params[:technique_id], user_id: @user.id)
    recommendation.update(status: 2)
    recommendation.update(ended_at: Time.zone.now) if recommendation.ended_at == nil
    flash[:info] = "You dislike Technique"
    redirect_to user_dashboard_page_path
  end

  private

  def search_coach(param)
    @coaches = Coach.search(param)
  end

  def filter_expertise(param)
    if param.present?
      @coaches = Problem.find_by(name: param).coaches
    end
  end

  def filter(param)
    param&.each do |data|
      @coaches = @coaches.where(data)
    end
  end

  def filter_users_count(param)
    if param.present?
      temp = @coaches
      array = []
      temp&.each do |coach|
        count = coach.invitations.where(status: 1).count
        param.each do |user_total|
          if user_total == '5' and count <= 5
            array << coach.id
          end
          if user_total == '5-10' and count > 5 and count <= 10
            array << coach.id
          end
          if user_total == '10-20' and count > 10 and count <= 20
            array << coach.id
          end
          if user_total == '20' and count > 20
            array << coach.id
          end
        end
      end
      array.uniq!
      @coaches = @coaches.where(id: array)
    end
  end

  def get_total_time_for_techniques(techniques)
    total_hours = 0
    techniques&.each do |t|
      if t.status == 'compeleted'
        total_hours += (t.ended_at - t.started_at)/60/60
      end
    end
    total_hours = total_hours.round
  end

  def get_current_time_for_techniques(techniques)
    current_hours = 0
    techniques&.each do |t|
      if t.status == 'in_progress'
        current_hours += (Time.zone.now - t.started_at)/60/60
      end
    end
    current_hours = current_hours.round
  end

  def update_params
    params.require(:user).permit(:name, :email, :avatar_user, :about, :age, :gender)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/user/_finish.html.erb
<div class="modal-header">
  <h5 class="modal-title">Congratulations!</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <p class="modal-message">You have finished completing the technique!</p>
  <p class="modal-message">Share with us your impressions and whether you like</p>
  <p class="modal-message">the technique.</p>
  <br>

  <p>Do you like this technique?</p>
</div>
<div class="modal-footer">

  <%= link_to 'I DON\'T LIKE IT', dislike_rating_path, method: :post, class: "btn btn-secondary" %>
  <%= link_to 'I LIKE IT', like_rating_path, method: :post, class: "btn btn-dark" %>

 </div>

app/views/user/_modal_ask_form.html.erb
<div class="modal-header">
  <% if @coach.avatar.attached? %>
    <img src="<%= url_for(@coach.avatar) %>" class= "modal-avatar-size  rounded-circle">
  <% else %>
    <img src="<%= asset_path('generic-user-icon-10.png') %>" class="modal-avatar-size  rounded-circle">
  <% end %>
  <h5 class="modal-title m-left"><%= @coach.name %></h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <p class="modal-message">Are you sure you want to end cooperation </p>
  <p class="modal-message">with this coach?</p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCEL</button>
  <!-- <button type="button" class="btn btn-dark">YES, I WANT</button> -->
  
  <%= link_to 'YES, I WANT',  end_cooperation_coach_invite_path(@invite.id), method: :delete, class: "btn btn-dark"%>

 </div>

app/views/user/finish.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'user/finish') %>");
$("#modal-window").modal();

app/views/user/modal_ask_form.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'user/modal_ask_form') %>");
$("#modal-window").modal();

app/views/user/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'user/new') %>");
$("#modal-window").modal();

app/views/user/show.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
  <nav class="navbar navbar-expand-lg nav_background fixed-top">
    <div class="container-fluid pad">
      <a class="navbar-brand logo logo-button" href="#">Logo</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Dashboard", user_dashboard_page_path, class: "nav-link nav-link-style" %>
          <%= link_to "My techniques", user_techniques_page_path, class: "nav-link nav-link-style" %>
          <%= link_to "Coaches", user_coahes_page_path, class: "nav-link nav-link-style" %>
        </div>
      </div>
      <div class="d-flex">
        <div class="envelope-block"><i class="bi bi-envelope"></i></div>

        <div class="bell-block">
          <i class="bi bi-bell" ></i>

        </div>
        <div class="me-3 dropdown">
          <% if @user.avatar_user.attached? %>
            <img src="<%= url_for(@user.avatar_user) %>" class= "rounded-circle size-image" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
          <% else %>
            <img src="<%= asset_path('generic-user-icon-10.png') %>" class="rounded-circle size-image" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Personal Information', update_profile_user_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Change Password', password_change_user_path, class: "dropdown-item" %></li>
          </ul>
        </div>
        <%= button_to 'LOG OUT', logout_path, method: :delete, class: "btn btn-sing-in" %>
      </div>
    </div>
  </nav>

  <div class="content-block">
    <% flash.each do |type, msg| %>
      <% if type == 'warning' %>
        <div class="alert alert-warning d-flex alert-dismissible fade show warning-color" role="alert">
          <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
          <div><%= msg %></div>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% elsif type == 'info' %>
        <div class="alert alert-primary  d-flex alert-dismissible fade show warning-color" role="alert">
          <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
          <div><%= msg %></div>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% else %>
        <div class="alert alert-danger  d-flex alert-dismissible fade show warning-color" role="alert">
          <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
          <div><%= msg %></div>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    <% end %>

    <%= content_for?(:content) ? yield(:content) : yield %>

  </div>

app/views/user/user_technique_detail.html.erb
<% content_for :content do %>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<h6>
  <%= link_to "Go back", user_dashboard_page_path, class: "bi bi-chevron-left link-back" %>
</h6>
<br>

<div class="row">

  <div class="col-8">
    <div class="row-width">
      <div class="row">
        <div class="col-9 mt">
          <%= @technique.title %>
        </div>
        <div class="col-3 mt-steps">
          <%= @recommendation.step-1  %> steps completed
        </div>


        <div class="col-12">
          <br>
          <div class="card">
            <div class="body_pad">
              <p class="step-title-card"><%= @step.title %></p>
              <span><%= @step.body %></span>
              <br>
            </div>
          </div>
        </div>
        <div class="col-12">
          <br>
          <div class="row">
              <div class="col-4">
                <% if @recommendation.step > 1  %>
                  <%= link_to 'RESTART', restart_path(technique_id: @recommendation.technique.id, step_id: @recommendation.step), method: :patch, class:"get_down_link"%>
                <% else %>
                  <div class="color-button-non-active">RESTART</div>
                <% end %>
              </div>
              <div class="col-4">
                Step <%= @recommendation.step %> of <%= @technique.total_steps %>
              </div>
              <div class="col-4">
                <% if @recommendation.step == @technique.total_steps %>
                  <%= link_to 'PASSED', user_rate_window_path(step_id: @step.number),  {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#modal-window', class: "btn btn-sing-up get_down_link"}  %>
                <% else %>
                  <%= link_to 'PASSED', user_technique_detail_path(step_id: @step.number), class:"btn btn-sing-up" %>
                <% end %>
              </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="col-4">
    <div class="row-width">

      <div class="row">

        <div class="col-6 mt-s-m active-page">
          <button id="my-users">Summary</button>
        </div>
        <div class="col-6 mt-s-m">
          <button id="waiting">Message</button>
        </div>


        <div class="col-12">
          <br>
            <div class="card h-100">
              <div class="item">
                <% if @technique.photo.attached? %>
                  <img src="<%= url_for(@technique.photo) %>" class= "card-img-top" alt="...">
                <% else %>
                  <img src="<%= asset_path('anthony-tran-vXymirxr5ac-unsplash.jpg') %>" class="card-img-top" alt="...">
                <% end %>
                <% if @technique.problems %>
                  <div class="tags-div-absolute">
                    <% @technique.problems.each do |problem|%>
                      <span class="tags-in-image "><%= problem.name%></span>
                    <% end %>
                  </div>
                <% end %>

              </div>
              <div class="card-body">
                <h6 class="title_card"><%= @technique.title %></h6>

                <p class="description"><%= @technique.description %></p>
                <div class="age">Age: <strong><%= @technique.age %> years</strong></div>
                <div class="gender">Gender: <strong><%= @technique.gender %></strong></div>
                <br>
                <div class="step">Steps:<strong> <%= @technique.total_steps %></strong></div>
                <div class="duration">Duration:<strong> <%= @technique.duration %> </strong></div>
                <div class="row">
                  <div class="col-2 image-coach-techinque">
                    <% if @recommendation.coach.avatar.attached? %>
                      <img src="<%= url_for(@recommendation.coach.avatar) %>" class= "rounded-circle notification-avatar">
                    <% else %>
                      <img src="<%= asset_path('generic-user-icon-10.png') %>" class="rounded-circle notification-avatar">
                    <% end %>
                  </div>
                  <div class="col-10 name-coach-techinque">
                    <%= @recommendation.coach.name %>
                  </div>
                </div>
                <ul class="hr">
                  <li><i class="bi bi-people"></i> <%= Recommendation.where(technique_id: @recommendation.technique.id).count%></li>
                  <li><i class="bi bi-hand-thumbs-up"></i> <%= Rating.where(technique_id: @recommendation.technique.id).sum(:like)%></li>
                  <li><i class="bi bi-hand-thumbs-down"></i>  <%= Rating.where(technique_id: @recommendation.technique.id).sum(:dislike)%></li>

              </div>
            </div>

        </div>

      </div>
    </div>
  </div>
</div>
<br>



<% end %>
<%= render template: "user/show" %>